# Site settings
title: "@Nedval"
email: Jrting@Nedval.me
description: > # this means to ignore newlines until "baseurl:"
comments: true

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pages.nedval.me" # the base hostname & protocol for your site
twitter_username:   Nedval
github_username:    Nedval
facebook_username:  Nedval

# Build settings
markdown: kramdown
